config/routes.rb
Rails.application.routes.draw do
  get 'bookings/show'
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: 'pages#dashboard'
  get "profil/:id", to: 'pages#profil', as: :profil

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :dogs, only: [ :show, :index, :new, :create, :edit, :update, :destroy ] do
    resources :bookings, only: [ :create ]
  end
  resources :bookings, only: [ :index, :edit, :update, :destroy ] do
    member do
      patch :update_status
    end
    resources :reviews, only: [ :create ]
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :dog
  belongs_to :user
  has_many :reviews

  validates :status, inclusion: { in: %w(approved pending rejected) }
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking)
    @bookings_pending = @bookings.select { |booking| booking.status == "pending" }
    @bookings_approved = @bookings.select { |booking| booking.status == "approved" }
    @bookings_rejected = @bookings.select { |booking| booking.status == "rejected" }
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @dog = Dog.find(params[:dog_id])
    @booking.dog = @dog
    @booking.user = current_user
    @booking.status = "pending"
    @bookings = policy_scope(Booking)
    @bookings_pending = @bookings.select { |booking| booking.status == "pending" }
    @bookings_approved = @bookings.select { |booking| booking.status == "approved" }
    @bookings_rejected = @bookings.select { |booking| booking.status == "rejected" }
    if @booking.save
      redirect_to bookings_path, notice: "Your booking has been registered"
    else
      render 'dogs/show'
    end

  end

  def edit
    @booking = Booking.find(params[:id])
    @dog = @booking.dog
    authorize @booking

    @bookings = policy_scope(Booking)
    @bookings_pending = @bookings.select { |booking| booking.status == "pending" }
    @bookings_approved = @bookings.select { |booking| booking.status == "approved" }
    @bookings_rejected = @bookings.select { |booking| booking.status == "rejected" }
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(booking_params)
    redirect_to bookings_path, notice: "Your booking has been successfully updated"

    @bookings = policy_scope(Booking)
    @bookings_pending = @bookings.select { |booking| booking.status == "pending" }
    @bookings_approved = @bookings.select { |booking| booking.status == "approved" }
    @bookings_rejected = @bookings.select { |booking| booking.status == "rejected" }
  end

  def update_status
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(status: params[:status])
    redirect_to dashboard_path, notice: "You have #{params[:status]} the booking"

    @bookings = policy_scope(Booking)
    @bookings_pending = @bookings.select { |booking| booking.status == "pending" }
    @bookings_approved = @bookings.select { |booking| booking.status == "approved" }
    @bookings_rejected = @bookings.select { |booking| booking.status == "rejected" }
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to bookings_path, notice: "Your booking has been deleted"

    @bookings = policy_scope(Booking)
    @bookings_pending = @bookings.select { |booking| booking.status == "pending" }
    @bookings_approved = @bookings.select { |booking| booking.status == "approved" }
    @bookings_rejected = @bookings.select { |booking| booking.status == "rejected" }
  end

  private

  def booking_params
    params.require(:booking).permit(:dog_id, :user_id, :start_date, :end_date, :status)
  end
end

app/views/bookings/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-6 my-3">
      <h5>🐶 Edit your booking with <strong><%= @dog.name.capitalize %></strong> 🐶</h5>
      <div class="form">
        <%= simple_form_for [@booking] do |f| %>
          <%= f.input :start_date, as: :date, html5: true, class: "form-control" %>
          <%= f.input :end_date, as: :date, html5: true, class: "form-control" %>
          <%= f.submit class: "button-first" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container js-bookings">
  <div class="row">
    <div class="col-12 col-lg-6 my-3">
      <div class="booking-cards">
        <h3>Upcoming bookings</h3>
        <% @bookings_pending.each do |booking| %>
          <% dog = Dog.find(booking.dog_id) %>
          <% user = User.find(dog.user_id) %>

          <div class="booking-card booking-card-pending">
            <% if dog.photos.attached? %>
              <%= cl_image_tag dog.photos[0].key, class:"booking-card-image" %>
            <% else %>
              <%= image_tag 'home.jpg', class:"booking-card-image" %>
              <% end %>
            <div class="booking-card-content">
              <div class="booking-card-title">
                <h4><%= link_to dog.name, dog_path(dog) %></h4>
                <div class="booking-card-date">
                <div>
                  <p>from</p>
                  <p>to</p>
                </div>
                <div class="dates">
                  <strong><%= booking.start_date %></strong>
                  <strong><%= booking.end_date %></strong>
                </div>
              </div>
              </div>
              <div class="booking-card-buttons">
                <%= link_to "#{user.first_name}'s profil", profil_path(user) %>
                <div class="mt-3">
                  <%= link_to "Cancel", booking_path(booking), method: :delete, data: { confirm: 'Are you sure you want to cancel this booking ?' }, class: "button-second" %>
                  <%= link_to "Edit", edit_booking_path(booking), class: "button-second" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-12 col-lg-6 my-3">
      <div class="booking-cards">
        <h3>Your past bookings</h3>

        <% @bookings_approved.each_with_index do |booking, index| %>
          <% dog = Dog.find(booking.dog_id) %>
          <% user = User.find(dog.user_id) %>
          <% review = Review.new %>

          <div class="booking-card booking-card-past">
            <% if dog.photos.attached? %>
              <%= cl_image_tag dog.photos[0].key, class:"booking-card-image" %>
            <% else %>
              <%= image_tag 'home.jpg', class:"booking-card-image" %>
            <% end %>
            <div class="booking-card-content">
              <div class="booking-card-title">
                <h4><%= link_to dog.name, dog_path(dog) %></h4>
                <div class="booking-card-date">
                  <div>
                    <p>from</p>
                    <p>to</p>
                  </div>
                  <div class="dates">
                    <strong><%= booking.start_date %></strong>
                    <strong><%= booking.end_date %></strong>
                  </div>
                </div>
              </div>
            </div>
            <div class="review">
              <% if booking.status == "approved" && booking.reviews.length == 0 %>
                <button type="button" class="button-second" data-toggle="modal" data-target="#create-review-modal<%=index%>">
                  Create a review
                </button>
              <% elsif booking.reviews.length != 0 %>
              <strong><p>your review :</p></strong>
                <%= booking.reviews[0].comment %>
                <p><%= booking.reviews[0].rating %> /10 </p>
              <% end %>
            </div>
          </div>

          <div class="modal fade" id="create-review-modal<%=index%>" tabindex="-1" role="dialog" aria-labelledby="review-modalTitle" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="create-review-modalTitle<%=index%>">Add your review</h5>
                </div>
                <div class="modal-body">
                  <div class="col-12 col-sm-6 my-3">
                    <div class="pb-3 px-3">
                      <%= simple_form_for [booking, review] do |f| %>
                        <%= f.input :comment, placeholder: 'Add your review' %>
                        <%= f.input :rating %>
                        <%= f.submit class:'button-first' %>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="button-second" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

<%# @bookings.each do |booking| %>
  <%# if policy(booking).edit? %>
    <%#= link_to "Update", booking_path(booking) %>
  <%# end %>
<%# end %>