config/routes.rb
Rails.application.routes.draw do
  get 'bookings/show'
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: 'pages#dashboard'
  get "profil/:id", to: 'pages#profil', as: :profil

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :dogs, only: [ :show, :index, :new, :create, :edit, :update, :destroy ] do
    resources :bookings, only: [ :create ]
  end
  resources :bookings, only: [ :index, :edit, :update, :destroy ] do
    member do
      patch :update_status
    end
    resources :reviews, only: [ :create ]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert notice-flash" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-flash" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="d-flex">
      <a id="footer-logo" href="/">
        <img class="logo" src="/assets/dog-logo-5ac0991c8e3ad13128a56af8100a26fb806b90012c152fb53fbeefbb855a3863.png">
      </a>
      <h1 class="top-margin">Truffe</h1>
    </div>
    <div class="container d-flex">
      <div class="main-menu-1">
        <a class= "icon-spaced" href="url">FAQ</a>
        <a class= "icon-spaced" href="url">Company</a>
        <a class= "icon-spaced" href="url">Press</a>
        <a class= "icon-spaced" href="url">Careers</a>
        <a class= "icon-spaced" href="url">Contact</a>
      </div>
      <div class="main-menu-2">
        <a class="social-media" href="url"><i class="fab fa-facebook-f"></i></a>
        <a class="social-media" href="url"><i class="fab fa-twitter"></i></i></a>
        <a class="social-media" href="url"><i class="fab fa-linkedin-in"></i></a>
        <a class="social-media" href="url"><i class="fab fa-instagram"></i></a>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="d-flex">
      <a class="btn btn-outline-secondary bottom-margin btn-color" class="legal-info">English</a>
      <div class="top-margin-2">
        <a href="url" class="legal-info">Legal Notice</a>
        <a href="url" class="legal-info">Privacy Policy</a>
        <a href="url" class="legal-info">Terms & Conditions</a>
      </div>
    </div>
    <div class="container" id="floor">
      <p style="margin-bottom: 30px;">Truffe International LLC is a company registered in France. Truffe is in conformity with the GDPR and CCPA and will never access or share your data. <br>For questions please contact the Truffe team any time. </p>
      <hr>
      <div style="margin-top: 25px;" class="footer-copyright center"> ©Truffe - Made with <i class="fas fa-paw"></i> by and for doggo lovers!</div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-truffe">

  <div class="flex">
    <%= link_to root_path do %>
      <%= image_tag "dog-logo.png", class: "logo" %>
    <% end %>
  </div>
  <%= render "shared/searchbar-small" %>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item js-notifications">
          <% if @bookings_approved.count > 2 || @bookings_rejected.count > 2  %>
            <div class="dropdown">
              <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="nav-item fas fa-bell nav-item-bell" style=" font-size: 20px; margin-top: 10px; margin-right: 18px;"></i>
              </a>

              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <% @bookings.each do |booking|  %>
                  <% if booking.status == "approved" %>
                    <%= link_to "⭐ #{Dog.find(booking.dog_id).name} is available", bookings_path, class: "dropdown-item"  %>
                  <% elsif booking.status == "rejected" %>
                    <%= link_to "⛔ #{Dog.find(booking.dog_id).name.capitalize} is busy", bookings_path, class: "dropdown-item"  %>
                  <% else %>
                    <%= link_to "⏳ #{Dog.find(booking.dog_id).name}'s answer pending", bookings_path, class: "dropdown-item"  %>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% else  %>
            <div class="dropdown">
              <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="nav-item far fa-bell nav-item-bell" style=" font-size: 20px; margin-top: 10px; margin-right: 18px;"></i>
              </a>

              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <% @bookings.each do |booking|  %>
                  <% if booking.status == "approved" %>
                    <%= link_to "⭐ #{Dog.find(booking.dog_id).name} is available", bookings_path, class: "dropdown-item"  %>
                  <% elsif booking.status == "rejected" %>
                    <%= link_to "⛔ #{Dog.find(booking.dog_id).name.capitalize} is busy", bookings_path, class: "dropdown-item"  %>
                  <% else %>
                    <%= link_to "⏳ #{Dog.find(booking.dog_id).name}'s answer pending", bookings_path, class: "dropdown-item"  %>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end  %>
        </li>
        <li class="nav-item">
          <%= link_to "My dogs", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Your bookings", bookings_path, class: "nav-link" %>
        </li>
        <div class="dropdown show">
          <a class="profile dropdown-toggle" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-align-justify"></i>
            <%= image_tag image_path('empty-profile.png'), class: "avatar" %>
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <%= link_to "Update profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_searchbar-index.html.erb
<%= form_tag dogs_path, class:"simple_form search-index", method: :get do %>
  <div class="search-bar search-transition">

    <div class="search-bar-item item-1">
      <p>Category</p>
      <%= select_tag :category,
        options_for_select(Dog::DOG_CATEGORY, selected: params[:category]),
        :include_blank => true %>
    </div>

    <div class="search-bar-item item-2">
    <p>Breed</p>
    <%= select_tag :breed,
        options_for_select(Dog.all.pluck(:breed).uniq, selected: params[:breed]),
        :include_blank => true %>
    </div>

    <div class="search-bar-item item-3">
    <p>Start date</p>
      <%= date_field_tag :start_date,
          params[:start_date],
          class: "datepicker" %>
    </div>

    <div class="search-bar-item item-4">
      <p>End date</p>
      <%= date_field_tag :end_date,
          params[:end_date],
          class: "datepicker"  %>
    </div>

  <button name="button" type="submit" class="btn btn-flat">
    <i class="fas fa-paw" style="font-size: 25px;"></i>
  </button>
  </div>
<% end %>

app/views/shared/_searchbar-small.html.erb
<%= form_tag dogs_path, class:"simple_form searchbar-small d-none", method: :get do %>
<div class="search-bar-small">

    <div class="search-bar-item item-small">
      <%= select_tag :category_small,
        options_for_select(Dog::DOG_CATEGORY, selected: params[:category]),
        :include_blank => true, prompt: 'Category' %>
    </div>

  <button name="button" type="submit" class="btn btn-flat">
    <i class="fas fa-paw" style="font-size: 16px;"></i>
  </button>
  </div>
<% end %>

app/views/shared/_searchbar.html.erb
<%= form_tag dogs_path, class:"simple_form search", method: :get do %>
  <div class="seach-bar">

    <div class="search-bar-item item-1">
      <p>Category</p>
      <%= select_tag :category,
        options_for_select(Dog::DOG_CATEGORY, selected: params[:category]),
        :include_blank => true %>
    </div>

    <div class="search-bar-item item-2">
    <p>Breed</p>
    <%= select_tag :breed,
        options_for_select(Dog.all.pluck(:breed).uniq, selected: params[:breed]),
        :include_blank => true %>
    </div>

    <div class="search-bar-item item-3">
    <p>Start date</p>
      <%= date_field_tag :start_date,
          params[:start_date],
          class: "datepicker"  %>
    </div>

    <div class="search-bar-item item-4">
      <p>End date</p>
      <%= date_field_tag :end_date,
          params[:end_date],
          class: "datepicker"  %>
    </div>

  <button name="button" type="submit" class="btn btn-flat">
    <i class="fas fa-paw" style="font-size: 25px;"></i>
  </button>
  </div>
<% end %>