config/routes.rb
Rails.application.routes.draw do
  get 'bookings/show'
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: 'pages#dashboard'
  get "profil/:id", to: 'pages#profil', as: :profil

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :dogs, only: [ :show, :index, :new, :create, :edit, :update, :destroy ] do
    resources :bookings, only: [ :create ]
  end
  resources :bookings, only: [ :index, :edit, :update, :destroy ] do
    member do
      patch :update_status
    end
    resources :reviews, only: [ :create ]
  end
end

app/views/pages/dashboard.html.erb
<div class="container-fluid" style="margin-top: 20px; margin-bottom: 20px;">

  <div class="row js-dashboard">
  </div>

  <div class="row">
    <div class="col-12 col-lg-6 py-3">
      <div>
        <%= link_to "Add a new truffle", new_dog_path, class:"button-first", style:"margin-left: 50px;" %>    
        
        <% if @dogs.empty? %>
          <hr>
          <em><small><p>You don't have any dog for the moment</p></small></em>
          <% end %>
      </div>
      <% unless @dogs.empty? %>
        <div>
          <div>
            <% @dogs.each do |dog| %>
              <div class="card-dog">
                <% if dog.photos.attached? %>
                  <div class="dog-card-images">
                    <div class="dog-card-big-img">
                      <%= cl_image_tag dog.photos[0].key %>
                    </div>
                    <div class="dog-card-small-img">
                      <%= cl_image_tag dog.photos[1].key %>
                      <%= cl_image_tag dog.photos[2].key %>
                    </div>
                  </div>
                <% else %>
                  <img src="https://source.unsplash.com/random"/>
                <% end %>
                <div class="d-flex">
                  <div class="card-dog-content">
                    <h5><%= link_to dog.name, dog_path(dog) %></h5>
                    <p>🐕 <%= dog.breed %> <br>
                                        🦴 <%= dog.category.capitalize %> <br>
                                        ⏳ <%= dog.age %> years old<br>
                                          <small><%= dog.description %></small></p>
                  </div>
                  <div class="card-dog-calendar">
                    <div class="calendar">
                      <div class="month">
                        <ul>
                          <li class="prev">&#10094;</li>
                          <li class="next">&#10095;</li>
                          <li>August 2021</li>
                        </ul>
                      </div>

                      <ul class="weekdays">
                        <li>Mo</li>
                        <li>Tu</li>
                        <li>We</li>
                        <li>Th</li>
                        <li>Fr</li>
                        <li>Sa</li>
                        <li>Su</li>
                      </ul>

                      <ul class="days">
                        <li class="day">1</li>
                        <li class="day">2</li>
                        <li class="day">3</li>
                        <li class="day">4</li>
                        <li class="day">5</li>
                        <li class="day">6</li>
                        <li class="day">7</li>
                        <li class="day">8</li>
                        <li class="day">9</li>
                        <li class="day">10</li>
                        <li class="day">11</li>
                        <li class="day">12</li>
                        <li class="day">13</li>
                        <li class="day">14</li>
                        <li class="day">15</li>
                        <li class="day">16</li>
                        <li class="day">17</li>
                        <li class="day">18</li>
                        <li class="day">19</li>
                        <li class="day">20</li>
                        <li class="day">21</li>
                        <li class="day">22</li>
                        <li class="day">23</li>
                        <li class="day">24</li>
                        <li class="day">25</li>
                        <li class="day">26</li>
                        <li class="day">27</li>
                        <li class="day">28</li>
                        <li class="day">29</li>
                        <li class="day">30</li>
                        <li class="day">31</li>
                      </ul>
                    </div>

                    <div class="d-flex mb-2 justify-content-end">
                      <%= link_to "Update", edit_dog_path(dog), class:"button-second", style:"margin-right: 20px;"%>
                      <%= link_to "Delete", dog_path(dog), method: :delete, data: {confirm: "Are you sure?"}, class:"button-second" %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-12 col-lg-6 py-3">

      <div>
        <h3>My pending booking requests</h3>
        <% if @bookings_pending.empty? %>
          <hr>
          <small><em><p>You don't have any booking requests yet !</p></em></small>
        <% else %>
          <% @bookings_pending.each do |booking| %>
            <% dog = Dog.find(booking.dog_id) %>
            <% user = User.find(booking.user_id) %>

            <div class="booking-card booking-card-pending">
              <% if dog.photos.attached? %>
                <%= cl_image_tag dog.photos[0].key, class:"booking-card-image" %>
              <% else %>
                <%= image_tag 'home.jpg', class:"booking-card-image" %>
              <% end %>
              <div class="booking-card-content">
                <div class="booking-card-title">
                  <h4><%= link_to dog.name, dog_path(dog) %></h4>
                  <div class="booking-card-date">
                    <div>
                      <p>from</p>
                      <p>to</p>
                    </div>
                    <div class="dates">
                      <strong><%= booking.start_date %></strong>
                      <strong><%= booking.end_date %></strong>
                    </div>
                  </div>
                </div>

                <div class="booking-card-buttons">
                  <%= link_to "#{user.first_name}'s profil", profil_path(user) %>
                  <div class="mt-3">
                    <%= link_to "Accept", update_status_booking_path(booking, status: "approved"), method: :patch, class: "button-second" %>
                    <%= link_to "Reject", update_status_booking_path(booking, status: "rejected"), method: :patch, class: "button-second" %>
                  </div>
                </div>

              </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <div>
        <h3>Bookings history</h3>
        <% if @bookings_pending.empty? %>
          <hr>    
          <small><em><p>You don't have any past bookings !</p></em></small>
        <% else %>
          <% @bookings_pending.each do |booking| %>
            <% dog = Dog.find(booking.dog_id) %>
            <% user = User.find(booking.user_id) %>

            <div class="booking-card booking-card-past">
              <% if dog.photos.attached? %>
                <%= cl_image_tag dog.photos[0].key, class:"booking-card-image" %>
              <% else %>
                <%= image_tag 'home.jpg', class:"booking-card-image" %>
              <% end %>
              <div class="booking-card-content">
                <div class="booking-card-title">
                  <h4><%= link_to dog.name, dog_path(dog) %></h4>
                  <div class="booking-card-date">
                    <div>
                      <p>from</p>
                      <p>to</p>
                    </div>
                    <div class="dates">
                      <strong><%= booking.start_date %></strong>
                      <strong><%= booking.end_date %></strong>
                    </div>
                  </div>  
                </div>
              </div>
              <div class="review">
                <% if booking.reviews.length != 0 %>
                  <strong><p><%= booking.reviews[0].user %></p></strong>
                  <%= booking.reviews[0].comment %>
                  <p><%= booking.reviews[0].rating %> /10 </p>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="cover cover-index">
  <div class="container">
    <h1>TRUFFE</h1>
    <p class="subtitle">
      <span id="banner-typed-text"></span>
    </p>
    <%= render "shared/searchbar" %>
  </div>
</div>

<div class="container">
  <h2 class="my-4 text-center">A dog, a hobby</h2>
  <div class="card-boxes margin">
    <div class="cards">
      <%= link_to dogs_path(category: "walk") do %>
        <div class="categories">
          <h5>Walk</h5>
          <%= image_tag "cards/walk.png" %>
        </div>
      <% end %>
    </div>
    <div class="cards">
      <%= link_to dogs_path(category: "sport") do %>
        <div class="categories">
          <h5>Sport</h5>
          <%= image_tag "cards/sport.png" %>
        </div>
      <% end %>
    </div>
     <div class="cards">
      <%= link_to dogs_path(category: "flirt") do %>
        <div class="categories">
          <h5>Flirting</h5>
          <%= image_tag "cards/flirting.png" %>
        </div>
      <% end %>
    </div>
     <div class="cards">
      <%= link_to dogs_path(category: "companion") do %>
        <div class="categories">
          <h5>Companion</h5>
          <%= image_tag "cards/companion.png" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="card-boxes margin">
     <div class="cards">
      <%= link_to dogs_path(category: "hunt") do %>
        <div class="categories">
          <h5>Hunting</h5>
          <%= image_tag "cards/hunt.png" %>
        </div>
      <% end %>
    </div>
    <div class="cards">
      <%= link_to dogs_path(category: "holiday") do %>
        <div class="categories">
          <h5>Holiday</h5>
          <%= image_tag "cards/holiday.png" %>
        </div>
      <% end %>
    </div>
    <div class="cards">
      <%= link_to dogs_path(category: "education") do %>
        <div class="categories">
          <h5>Education</h5>
          <%= image_tag "cards/education.png" %>
        </div>
      <% end %>
    </div>
    <div class="cards">
      <%= link_to dogs_path(category: "breeding") do %>
        <div class="categories">
          <h5>Breeding</h5>
          <%= image_tag "cards/breeding.png" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="margin-top">
  <h2 class="my-4 margin text-center">Meet our top dogs 🏆</h2>
  <% unless @dogs.empty? %>
    <div class="container flex-carousel">
      <div class="left-transparent">
        <p></p>
      </div>
        <p></p>
      <div class="right-transparent">
      </div>
      <div class="dog-carousel">
        <div class="dogs-container">
          <% @dogs.each do |dog| %>
            <%= link_to dog_path(dog) do %>
              <div class="card cards mx-3">
                <div class="dog-name">
                  <%= dog.name %>
                </div>
                <div class="dog-review">
                  <% aggregated_reviews = dog.reviews.sum(:rating) / dog.reviews.size %>
                  <p>⭐ <%= aggregated_reviews.round(1) %> / 10</p>
                </div>
                <div class="top-dog-picture">
                  <%= cl_image_tag dog.photos[0].key, crop: :fill %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="margin-top margin-bottom mb-5" >
  <%= link_to new_dog_path(category: "holiday") do %>
    <div class="card-owner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path "cards/dogowner.png" %>')">
      <div class="">
        Become a Truffe dog owner
      </div>
      <div class="owner-paragraph">
        Enable your dog to become part of Truffe family! <br> Truffe is the friendliest and safest community to find the right person <br>to take care of your doggie once you're away for a couple of days
      </div>
      <div>
        <p style="margin-top: 30px;" class="button-first">Become a dog owner</p>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/profil.html.erb
<h1>Renter's profil</h1>